# -*- coding: utf-8 -*-
"""PLN_Zipf_Law_abreviation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S35-q9SkRzaCN-CXwkbL2eshuUf02f4N
"""

#NLP_Zipfs_law_of_abbreviation
#Authors: Luiz Quadros, Mengqi Liu and Nur Rodriguez Boada.

#We will start by importing the necessary packages for our task
import urllib.request
from datasets import load_dataset
import re
import pandas as pd
from collections import Counter
import matplotlib.pyplot as plt

#First things first, we will start by importing a Poetry Dataset in English
english_dataset = load_dataset("merve/poetry")
#Now, we will join all the poems by deleting any spaces. Since they are in train/poem section, we will specify it. Also, we will lowercase all letters
english_poems = " ".join(english_dataset['train']['content']).lower()
#Finally, to get a list of words, we will quickly do so by using regex
english_words = re.findall(r"\b[a-z']*[a-z][a-z']*\b", english_poems)

#If we print them out, we can see the list, by applying (len) we make sure that the number is large enough to contain the words in the poems
print(english_words)
len(english_words)

#Now it's time for the Spanish dataset. We start by loading it
spanish_dataset = load_dataset("jorge-henao/disco_poetry_spanish")
#Then, we just do the same as we did with English
spanish_poems = " ".join(spanish_dataset['train']['text']).lower()
spanish_words = re.findall(r"\b[a-záéíóúüñ']+\b",spanish_poems)

#We run the same comprovations
print(spanish_words)
len(spanish_words)

#Now is time to calculate our most frequent words. We'll start (once again) with English
#First, we count each word
word_counts_English = Counter(english_words)
#We create our table with two columns: word and frequency
df_english = pd.DataFrame(word_counts_English.items(), columns=['word', 'frequency'])
#Now, to fully see the effects of Zipf's Law of Abbreviation, we need to check how long each word is. For that, we add a length column.
df_english['length'] = df_english['word'].apply(len)
#Now it is time to rank them and make them easier to interpret. To do so we will order by frequency and then, we will give them a new index and get rid of the one we had prior to ranking the words
df_english = df_english.sort_values(by='frequency', ascending=False).reset_index(drop=True)
#Finally, we assign a rank to each word. We use the method=min code to assign the same rank to words with the same frequency
df_english['rank'] = df_english['frequency'].rank(ascending=False, method='min').astype(int)
#To finish, let's print the whole thing
print (df_english)

#Now, to make the Spanish one we follow the exact same steps, but changing everything where we typed English before for Spanish
word_counts_Spanish = Counter(spanish_words)
df_spanish = pd.DataFrame(word_counts_Spanish.items(), columns=['word', 'frequency'])
df_spanish['length'] = df_spanish['word'].apply(len)
df_spanish = df_spanish.sort_values(by='frequency', ascending=False).reset_index(drop=True)
df_spanish['rank'] = df_spanish['frequency'].rank(ascending=False, method='min').astype(int)
print(df_spanish)

#To see the Top 10 words of each language is very easy, we just ask for the 10 at the top. We can do this with any number in our rank
print("TOP 10 English Words")
print(df_english.head(10))
print()
print("TOP 10 Spanish Words")
print(df_spanish.head(10))

plt.scatter(df_english['length'], df_english['frequency'], color='royalblue', s=25, alpha=0.5)
plt.yscale('log')
plt.xticks(range(1, 21))
plt.title("Words in English Poems")
plt.xlabel("Word Length")
plt.ylabel("Word Frequency (log scale)")
plt.grid(True, linestyle='--')
plt.show()

plt.scatter(df_spanish['length'], df_spanish['frequency'], color='green', s=25, alpha=0.3)
plt.yscale('log')
plt.xticks(range(1, 26))
plt.title("Words in Spanish Poems")
plt.xlabel("Word Length")
plt.ylabel("Word Frequency (log scale)")
plt.grid(True, linestyle='--', alpha=0.5)
plt.show()
